spring.application.name=gerenciador-tarefa

# ==========================================
# Configuração do Banco H2 (Em Memória)
# ==========================================
spring.datasource.url=jdbc:h2:mem:tarefasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# Configuração do JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# H2 Web Console (Acesso em: /h2-console)
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura-para-desafio-gerenciador-tarefas-2026}
api.security.token.expiration-hours=24

